#!/bin/sh

max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
diff=`expr $max / 15`
val=$(cat /sys/class/backlight/intel_backlight/brightness)

if [ "$1" = "+" ] ; then
  val=`expr $val + $diff`
else
  val=`expr $val - $diff`
fi

val=$(( $val > $diff ? $val : $diff ))
val=$(( $val < $max ? $val : $max ))

echo $val | tee /sys/class/backlight/intel_backlight/brightness
